site_name: Yoshi Was Here

theme:
  name: material
  palette:
  - scheme: default
    primary: grey
    accent: grey
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate
    primary: grey
    accent: grey
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate

