name: MkDocs Deploy (gh-deploy)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install mkdocs-material

      - name: Deploy site using MkDocs
        run: mkdocs gh-deploy --force
